server:
  port: 8081

spring:
  application:
    name: spring-oauth2-resourceserver-websocket
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    relay:
      host: ${RELAY_HOST:localhost}
      port: ${RELAY_PORT:61613}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  data:
    redis:
      port: 6379
      host: localhost
      #url:
      #username:
      #password:

logging:
  level:
    org.springframework.data: DEBUG
    sql: debug